---
- name: Allow OpenVPN through the firewall
  command: "{{ item }}"
  with_items: "{{ openvpn_firewall_rules }}"

- name: Allow OpenVPN over IPv6 through the firewall
  command: "{{ item }}"
  with_items: "{{ openvpn_ipv6_firewall_rules }}"
  when: streisand_ipv6_address is defined

- name: Ensure UFW allows DNS requests from OpenVPN clients
  ufw:
    to_port: "53"
    proto: "udp"
    rule: "allow"
    from_ip: "{{ openvpn_server_tcp_ipv4_address }}"

- name: Ensure UFW allows DNS requests from OpenVPN UDP clients
  ufw:
    to_port: "53"
    proto: "udp"
    rule: "allow"
    from_ip: "{{ openvpn_server_udp_ipv4_address }}"

- name: Ensure UFW allows DNS requests from OpenVPN IPv6 clients
  ufw:
    to_port: "53"
    proto: "udp"
    rule: "allow"
    from_ip: "{{ openvpn_server_tcp_ipv6_address }}"
  when: streisand_ipv6_address is defined

- name: Ensure UFW allows DNS requests from OpenVPN UDP IPv6 clients
  ufw:
    to_port: "53"
    proto: "udp"
    rule: "allow"
    from_ip: "{{ openvpn_server_udp_ipv6_address }}"
  when: streisand_ipv6_address is defined

- name: Ensure UFW allows OpenVPN
  ufw:
    to_port: "{{ openvpn_port }}"
    proto: "tcp"
    rule: "allow"

- name: Ensure UFW allows OpenVPN over UDP
  ufw:
    to_port: "{{ openvpn_port_udp }}"
    proto: "udp"
    rule: "allow"

- name: Install the OpenVPN iptables service file
  template:
    src: openvpn-iptables.service.j2
    dest: /etc/systemd/system/openvpn-iptables.service
    mode: 0644

- name: Install the OpenVPN IPv6 iptables service file
  template:
    src: openvpn-ipv6tables.service.j2
    dest: /etc/systemd/system/openvpn-ipv6tables.service
    mode: 0644
  when: streisand_ipv6_address is defined

- name: Enable the openvpn-iptables service
  systemd:
    daemon_reload: yes
    name: openvpn-iptables.service
    enabled: yes
    state: started

- name: Enable the openvpn-ipv6tables service
  systemd:
    daemon_reload: yes
    name: openvpn-ipv6tables.service
    enabled: yes
    state: started
  when: streisand_ipv6_address is defined
