---
- name: "Ensure UFW allows DNS requests from WireGuard clients"
  ufw:
    to_port: "53"
    proto: "udp"
    rule: "allow"
    from_ip: "10.192.122.0/24"

- name: "Ensure UFW allows DNS requests from WireGuard IPv6 clients"
  ufw:
    to_port: "53"
    proto: "udp"
    rule: "allow"
    from_ip: "fde9:7496:c3d7:a47f::/64"
  when: streisand_ipv6_address is defined

- name: "Ensure UFW allows WireGuard"
  ufw:
    to_port: "{{ wireguard_port }}"
    proto: "udp"
    rule: "allow"

- name: "Allow WireGuard through the firewall"
  command: "{{ item }}"
  with_items: "{{ wireguard_firewall_rules }}"

- name: "Allow WireGuard over IPv6 through the firewall"
  command: "{{ item }}"
  with_items: "{{ wireguard_firewallv6_rules }}"
  when: streisand_ipv6_addres is defined

- name: "Add WireGuard firewall persistence service to init"
  template:
    src: wireguard-iptables.service.j2
    dest: /etc/systemd/system/wireguard-iptables.service
    mode: 0644
    wg_firewall_rules: "{{ wireguard_firewall_rules }}"

- name: "Add WireGuard IPv6 firewall persistence service to init"
  template:
    src: wireguard-iptables.service.j2
    dest: /etc/systemd/system/wireguard-ipv6tables.service
    mode: 0644
    wg_firewall_rules: "{{ wireguard_firewallv6_rules }}"
  when: streisand_ipv6_address is defined

- name: "Enable the wireguard-iptables service"
  systemd:
    daemon_reload: yes
    name: wireguard-iptables.service
    enabled: yes
    state: started

- name: "Enable the wireguard-ipv6tables service"
  systemd:
    daemon_reload: yes
    name: wireguard-ipv6tables.service
    enabled: yes
    state: started
