---
- name: Get the default SSH key
  command: cat ~/.ssh/id_rsa.pub
  register: ssh_key

- name: Create the Lightsail instance
  lightsail:
    state: present
    name: "{{ lightsail_instance_name }}"
    region: "{{ lightsail_region }}"
    zone: "{{ lightsail_zone }}"
    blueprint_id: "{{ lightsail_blueprint_id }}"
    bundle_id: "{{ lightsail_bundle_id }}"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    wait_timeout: 500
  register: streisand_server

- name: Debug the output
  debug:
    msg: "Streisad Server is {{ streisand_server }}"

- name: Wait until the server has finished booting and OpenSSH is accepting connections
  wait_for:
    host: "{{ streisand_server.instance.public_ip_address }}"
    port: 22
    search_regex: OpenSSH
    timeout: 600

- name: Set the streisand_ipv4_address variable
  set_fact:
    streisand_ipv4_address: "{{ streisand_server.instance.public_ip_address }}"

- name: Set the streisand_server_name variable
  set_fact:
    streisand_server_name: "{{ lightsail_instance_name | regex_replace('\\s', '_') }}"

- name: Create the in-memory inventory group
  add_host:
    name: "{{ streisand_ipv4_address }}"
    groups: streisand-host
    ansible_user: ubuntu
    ansible_become: yes

- name: New Lightsail servers are occasionally slow to process incoming SSH connections even after the OpenSSH daemon has started up. Pause for 90 seconds.
  pause:
    seconds: 90
