---
- name: Install the Libreswan dependencies that are required for compilation
  apt:
    name: "{{ item }}"
  with_items: "{{ libreswan_compilation_dependencies }}"

- name: Install xmlto (without the extraordinarily large number of packages it normally recommends)
  apt:
    name: xmlto
    install_recommends: no

- name: Retrieve the Libreswan source code
  include_role:
    name: download-and-verify
  vars:
    project_name: "The Libreswan Project"
    project_signer: "The Libreswan team"
    project_signing_key: "{{ libreswan_developers_key_id }}"
    project_expected_fingerprint: "{{ libreswan_developers_expected_fingerprint }}"
    project_download_location: "{{ libreswan_src_directory }}"
    project_download_urls: "{{ libreswan_download_urls }}"

- name: Extract the Libreswan source code
  unarchive:
    copy: no
    src: "{{ libreswan_source_location }}"
    dest: /usr/local/src
    owner: root
    group: root
    creates: "{{ libreswan_compilation_directory }}/README"

- name: Compile and install Libreswan (this will take a while)
  shell: make -j {{ ansible_processor_cores }} programs && make install
  args:
    chdir: "{{ libreswan_compilation_directory }}"

- name: Generate IPsec configuration file
  template:
    src: ipsec.conf.j2
    dest: /etc/ipsec.conf
    owner: root
    group: root
    mode: 0644

- name: Copy the ipsec.secrets file
  copy:
    src: ipsec.secrets
    dest: /etc/ipsec.d/ipsec.secrets
    owner: root
    group: root
    mode: 0600

- name: Copy the modified rsyslog configuration into place that prevents Libreswan traffic from being logged
  copy:
    src: 40-ipsec.rsyslog.conf
    dest: /etc/rsyslog.d/40-ipsec.conf
    owner: root
    group: root
    mode: 0644
  notify: Restart rsyslog for Libreswan

- name: Generate a certificate database file
  script: generate-certificate-database.sh
  args:
    creates: /etc/ipsec.d/cert8.db

- name: "Install IPsec iptables service file"
  template:
    src: ipsec-iptables.service.j2
    dest: /etc/systemd/system/ipsec-iptables.service
    mode: 0644

- name: "Enable the ipsec-iptables service"
  systemd:
    daemon_reload: yes
    name: ipsec-iptables.service
    enabled: yes
    state: started
