---
- name: Generate the L2TP-IPsec configuration file
  template:
    src: ipsec.conf.j2
    dest: /etc/ipsec.d/l2tp.conf
    owner: root
    group: root
    mode: 0644

- name: Generate a random IPsec pre-shared key
  shell: "{{ streisand_word_gen.psk }}  > {{ ipsec_preshared_key_file }}"
  args:
    creates: "{{ ipsec_preshared_key_file }}"

- name: Set permissions on the IPsec pre-shared key
  file:
    path: "{{ ipsec_preshared_key_file }}"
    owner: root
    group: root
    mode: 0600

- name: Register the IPsec pre-shared key
  command: cat {{ ipsec_preshared_key_file }}
  register: ipsec_preshared_key
  changed_when: False

- name: Register the IPsec pre-shared key as base64
  shell: cat {{ ipsec_preshared_key_file }} | tr -d '\n' | base64
  register: ipsec_preshared_key_base64
  changed_when: False

- name: Add the IPsec PSK to ipsec.secrets
  shell: "echo '{{ ansible_default_ipv4.address }} %any:  PSK {{ ipsec_preshared_key.stdout }}' >> /etc/ipsec.secrets" 

#{% if streisand_ikev2_enabled %}
#{{ ansible_default_ipv4.address }} %any:  RSA
#{% endif %}

- name: Generate xl2tpd configuration file
  template:
    src: xl2tpd.conf.j2
    dest: /etc/xl2tpd/xl2tpd.conf
    owner: root
    group: root
    mode: 0644

- name: Copy xl2tpd secrets file
  copy:
    src: l2tp-secrets
    dest: /etc/xl2tpd/l2tp-secrets
    owner: root
    group: root
    mode: 0600

- name: Generate PPP options file
  template:
    src: options.xl2tpd.j2
    dest: "{{ ppp_options_file }}"
    owner: root
    group: root
    mode: 0644

- name: Generate a random CHAP password
  shell: "{{ streisand_word_gen.weak_password }} > {{ chap_password_file }}"
  args:
    creates: "{{ chap_password_file }}"

- name: Set permissions on the CHAP password
  file:
    path: "{{ chap_password_file }}"
    owner: root
    group: root
    mode: 0600

- name: Register the CHAP password
  command: cat {{ chap_password_file }}
  register: chap_password
  changed_when: False

- name: Generate CHAP secrets file
  template:
    src: chap-secrets.j2
    dest: /etc/ppp/chap-secrets
    owner: root
    group: root
    mode: 0600

# Ensure l2tp firewall rules are in place
- import_tasks: firewall.yml

- name: Enable and start ipsec and l2tp services
  systemd:
    daemon_reload: yes
    name: "{{ item }}"
    enabled: yes
    state: restarted
  with_items:
    - ipsec
    - xl2tpd

# Generate l2tp instructions and mobile profiles
- import_tasks: docs.yml
