---
- name: Ensure UFW allows DNS requests from OpenConnect clients
  ufw:
    to_port: "53"
    proto: "udp"
    rule: "allow"
    from_ip: "{{ ocserv_ipv4_network }}"

- name: Ensure UFW allows DNS requests from OpenConnect IPv6 clients
  ufw:
    to_port: "53"
    proto: "udp"
    rule: "allow"
    from_ip: "{{ ocserv_ipv6_network }}"
  when: streisand_ipv6_address is defined

- name: Ensure UFW allows OpenConnect (ocserv)
  ufw:
    to_port: "{{ ocserv_port }}"
    proto: "any"
    rule: "allow"

- name: Install the ocserv iptables service file
  template:
    src: ocserv-iptables.service.j2
    dest: /etc/systemd/system/ocserv-iptables.service
    mode: 0644

- name: Enable the ocserv-iptables service
  systemd:
    daemon_reload: yes
    name: ocserv-iptables.service
    enabled: yes
    state: started

- name: Install the ocserv ipv6tables service file
  template:
    src: ocserv-ipv6tables.service.j2
    dest: /etc/systemd/system/ocserv-ipv6tables.service
    mode: 0644
  when: streisand_ipv6_address is defined

- name: Enable the ocserv-iptables service
  systemd:
    daemon_reload: yes
    name: ocserv-iptables.service
    enabled: yes
    state: started
  when: streisand_ipv6_address is defined
