---
- import_tasks: web-gateway.yml
  when: streisand_nginx_enabled

  # TODO:
  #   Add to CI testing https://github.com/StreisandEffect/streisand/issues/643
- block:
    - name: Keep a copy of our diagnostics on the server
      copy:
        src: ../../../../streisand-diagnostics.md
        dest: "{{ streisand_gateway_location }}/streisand-diagnostics.md"

    # generate the streisand server instructions and documentation
    - include_tasks: docs.yml

    # fetch and clean up
    - include_tasks: fetch-and-cleanup.yml

    - meta: flush_handlers

    - block:
        - name: Success!
          pause:
            prompt: "Server setup is complete. The `{{ streisand_server_name }}.html` instructions file in the generated-docs folder is ready to give to friends, family members, and fellow activists. Press Enter to continue."

        - name: Attempt to open the instructions on Linux (if applicable). Errors in this task are ignored because the `xdg-open` command is not always available.
          local_action: command xdg-open ../{{ streisand_local_directory }}/{{ streisand_server_name }}.html
          ignore_errors: yes
          when: hostvars['127.0.0.1']['ansible_system'] == "Linux"
          become: no

        - name: Open the instructions on macOS (if applicable)
          local_action: command open ../{{ streisand_local_directory }}/{{ streisand_server_name }}.html
          when: hostvars['127.0.0.1']['ansible_system'] == "Darwin"
          become: no
      when: not streisand_noninteractive
  when: not streisand_ci
