---
- name: Provision the Lightsail Server
# ====================================
  hosts: localhost
  connection: local
  gather_facts: yes

  vars:
    zones:
      "1": "us-east-1a"
      "2": "us-east-1b"
      "3": "us-east-1c"
      "4": "us-east-1d"
      "5": "us-east-1e"


  vars_prompt:
    #- name: "lightsail_region_var"
    #  prompt: |
    #    In what region should the server be located?
    #      1. US East       (Northern Virginia)
    #    Please choose the number of your region. Press enter for default (#1) region.
    #  default: "1"
    #  private: no

    - name: "lightsail_zone_var"
      prompt: |
        In what availability zone would you like your server to be located?
          1. US East 1A      (Northern Virginia)
          2. US East 1B      (Northern Virginia)
          3. US East 1C      (Northern Virginia)
          4. US East 1D      (Northern Virginia)
          5. US East 1E      (Northern Virginia)
        Please choose the number of your zone. Press enter for default zone (#1).
      default: "1"
      private: no

    - name: "lightsail_instance_name"
      prompt: "\nWhat should the server be named? Press enter for default (streisand).\n"
      default: "streisand"
      private: no

    - name: "aws_access_key"
      prompt: "\n\nThe following information can be found in the IAM Management Console.\nhttps://console.aws.amazon.com/iam/home?#security_credential\n\nWhat is your AWS Access Key ID?\n"
      private: no

    - name: "aws_secret_key"
      prompt: "\nWhat is your AWS Secret Access Key?\n"
      private: no

    - name: "confirmation"
      prompt: "\nStreisand will now set up your server. This process usually takes around ten minutes. Press Enter to begin setup...\n"

  pre_tasks:
    - name: Set the Lightsail region fact
      set_fact:
        lightsail_region: "us-east-1"

    - name: Set the Lightsail Availability zone fact
      set_fact:
        lightsail_zone: "{{ lightsail_zone_var }}"

    - debug:
        msg: "Lightsail region: {{ lightsail_region }}"

    - debug:
        msg: "Lightsail zone: {{ lightsail_zone }}"

  roles:
    - genesis-amazon-lightsail


- include: cloud-status.yml
- include: streisand.yml
