---
- name: Provision the Lightsail Server
# ====================================
  hosts: localhost
  connection: local
  gather_facts: yes

  vars:
    zones:
      "1":  "us-east-1"
      "2":  "us-east-2"
      "3":  "us-west-2"
      "4":  "eu-west-1"
      "5":  "eu-west-2"
      "6":  "eu-central-1"
      "7":  "ap-southeast-1"
      "8":  "ap-southeast-2"
      "9":  "ap-northeast-1"
      "10": "ap-south-1"


  vars_prompt:
    #- name: "lightsail_region_var"
    #  prompt: |
    #    In what region should the server be located?
    #      1. US East       (Ohio)
    #    Please choose the number of your region. Press enter for default (#1) region.
    #  default: "1"
    #  private: no

    - name: "lightsail_zone_var"
      prompt: |
        In what availability zone would you like your server to be located?
          1. US East        (N. Virginia)
          2. US East        (Ohio)
          3. US West        (Oregon)
          4. EU West        (Ireland)
          5. EU West        (London)
          6. EU Central     (Frankfurt)
          7. Asia Pacific   (Signapore)
          8. Aisa Pacific   (Sydney)
          9. Asia Pacific   (Tokyo)
          10. Asia Pacific  (Mumbai)
        Please choose the number of your zone. Press enter for default zone (#1).
      default: "1"
      private: no

    - name: "lightsail_instance_name"
      prompt: "\nWhat should the server be named? Press enter for default (streisand).\n"
      default: "streisand"
      private: no

    - name: "aws_access_key"
      prompt: "\n\nThe following information can be found in the IAM Management Console.\nhttps://console.aws.amazon.com/iam/home?#security_credential\n\nWhat is your AWS Access Key ID?\n"
      private: no

    - name: "aws_secret_key"
      prompt: "\nWhat is your AWS Secret Access Key?\n"
      private: no

    - name: "lightsail_ssh_name"
      prompt: "\n\nThe following information can be found on your Amazon Lightsail accounts panel.\nhttps://lightsail.aws.amazon.com/ls/webapp/account\n\nWhat is the name of the Lightsail SSH key that you would like to use?\n  * This key should match your .ssh/id_rsa.pub file.\n"
      private: no

    - name: "confirmation"
      prompt: "\nStreisand will now set up your server. This process usually takes around ten minutes. Press Enter to begin setup...\n"

  pre_tasks:
    - name: Set the Lightsail region fact
      set_fact:
        lightsail_region: "us-east-1"

    - name: Set the Lightsail Availability zone fact
      set_fact:
        lightsail_zone: "{{ zones[lightsail_zone_var] }}"

    - debug:
        msg: "Lightsail region: {{ lightsail_region }}"

    - debug:
        msg: "Lightsail zone: {{ lightsail_zone }}"

  roles:
    - genesis-amazon-lightsail


- include: cloud-status.yml
- include: streisand.yml
