---
libreswan_compilation_dependencies:
  - bison
  - flex
  - libcap-ng-dev
  - libcap-ng-utils
  - libcurl4-nss-dev
  - libevent-dev
  - libnspr4-dev
  - libnss3-dev
  - libnss3-tools
  - libpam0g-dev
  - libselinux1-dev
  - libsystemd-dev
  - libunbound-dev
  - pkg-config

libreswan_version: "3.20"
libreswan_src_directory: "/usr/local/src"
libreswan_compilation_directory: "{{ libreswan_src_directory }}/libreswan-{{ libreswan_version }}"
libreswan_source_filename: "libreswan-{{ libreswan_version }}.tar.gz"
libreswan_sig_filename: "{{ libreswan_source_filename }}.asc"
libreswan_source_location: "/usr/local/src/{{ libreswan_source_filename }}"
libreswan_developers_key_id: "0x85FF4B43B30FC6F9"
libreswan_developers_expected_fingerprint: "Key fingerprint = 907E 790F 25C1 E8E5 61CD  73B5 85FF 4B43 B30F C6F9"
