---
- name: Create the ikev2 certificates directory directory
  file:
    path: "{{ ikev2_path }}"
    owner: root
    group: root
    mode: 0750
    state: directory

- include_role:
    name: certificates
  vars:
    ca_path:            "{{ ikev2_path }}"
    tls_ca:             "{{ ikev2_ca }}"
    tls_client_path:    "{{ ikev2_path }}"
    vpn_name:           "ipsec_ikev2"
    generate_ca_server: yes
    generate_client:    yes
    generate_pkcs:      yes
    tls_key_size:                "{{ ikev2_key_size }}"
    tls_request_subject:         "{{ ikev2_request_subject }}"
    tls_server_common_name_file: "{{ ikev2_server_common_name_file }}"
    tls_sans:
      - "{{ streisand_ipv4_address }}"

- name: Generate the IPsec PSK secrets file
  template:
    src: ipsec.ikev2.secrets.j2
    dest: /etc/ipsec.d/ipsec.ikev2.secrets
    owner: root
    group: root
    mode: 0600

- name: Generate the IPsec-IKEv2 configuration file
  template:
    src: ipsec.conf.j2
    dest: /etc/ipsec.d/ikev2.conf
    owner: root
    group: root
    mode: 0644
  notify: Restart Libreswan
