---
- name: Generate the IPSec-IKEv2 configuration file
  template:
    src: ipsec.conf.j2
    dest: /etc/ipsec.d/ikev2.conf
    owner: root
    group: root
    mode: 0644
  notify: Restart Libreswan

- name: Create directories for clients
  file:
    path: "{{ ikev2_path }}/{{ client_name.stdout }}"
    state: directory
  with_items: "{{ vpn_client_names.results }}"
  loop_control:
    loop_var: "client_name"
    label: "{{ client_name.item }}"

- include_role:
    name: certificates
  vars:
    ca_path:            "{{ ikev2_path }}"
    tls_ca:             "{{ ikev2_path }}"
    tls_client_path:    "{{ ikev2_path }}"
    generate_ca_server: yes
    generate_client:    yes
    tls_key_size:                "{{ ikev2_key_size }}"
    tls_request_subject:         "{{ ikev2_request_subject }}"
    tls_server_common_name_file: "{{ ikev2_server_common_name_file }}"
    tls_sans:
      - "{{ streisand_ipv4_address }}"

- name: Generate RSA keys for the CA and Server
  command: openssl genrsa -out {{ item }}.key {{ ikev2_key_size }}
  args:
    chdir: "{{ ikev2_path }}"
    creates: "{{ item }}.key"
  with_items:
    - ca
    - server



